#!/usr/bin/env python3
"""
Bishop/Eastern Sierra and Sequoia/Kings Canyon Data
Sources: NPS.gov, USFS Inyo NF, Bishop Visitor Center, Mountain Project
"""

BISHOP_EASTERN_SIERRA_DATA = [
    # WALKS
    {
        "name": "Bishop Creek Pathway",
        "place_type": "starting_point",
        "lat": 37.3611,
        "lng": -118.3953,
        "address": "Bishop Creek Pathway, Bishop, CA 93514",
        "parking_notes": "City park lots along pathway; free; paved access",
        "kid_friendly": True,
        "activity_type": "walk",
        "difficulty": 1,
        "distance_km": 5.0,
        "elevation_gain_m": 30,
        "notes": "3-mile paved urban trail along Bishop Creek through town. Multiple access points. Interpretive signs on local history and ecology. Links to parks and shopping. Pleasant even in midday heat.",
        "sources": [("https://www.bishopvisitor.com/recreation", "official")]
    },
    {
        "name": "Intake II Lake Walk",
        "place_type": "trailhead",
        "lat": 37.2361,
        "lng": -118.6111,
        "address": "South Lake Rd, Bishop, CA 93514",
        "parking_notes": "USFS fee lot $5; day use only; outhouses available",
        "kid_friendly": True,
        "activity_type": "walk",
        "difficulty": 1,
        "distance_km": 3.2,
        "elevation_gain_m": 25,
        "notes": "2-mile lakeside walk on service road. Fishing access, aspen groves. Part of Bishop Creek Canyon system. Good intro to Eastern Sierra at 7,600 ft. Fall colors spectacular in October.",
        "sources": [("https://www.fs.usda.gov/recarea/inyo/recarea/?recid=20323", "official")]
    },
    {
        "name": "Weir Lake Walk",
        "place_type": "trailhead",
        "lat": 37.2861,
        "lng": -118.5833,
        "address": "South Lake Rd, Bishop, CA 93514",
        "parking_notes": "USFS fee lot $5; no facilities; closes for snow Nov-May",
        "kid_friendly": True,
        "activity_type": "walk",
        "difficulty": 1,
        "distance_km": 1.5,
        "elevation_gain_m": 15,
        "notes": "1-mile stroll around Weir Lake at 9,000 ft. Small lake with aspen and willow. Good fishing. Quiet alternative to larger South Lake. Often frozen until June.",
        "sources": [("https://www.fs.usda.gov/recarea/inyo/recarea/?recid=20323", "official")]
    },
    
    # FAMILY WALKS
    {
        "name": "Pine Creek Pack Station Walk",
        "place_type": "trailhead",
        "lat": 37.4611,
        "lng": -118.6683,
        "address": "Pine Creek Rd, Bishop, CA 93514",
        "parking_notes": "USFS lot at pack station; free; outhouses; seasonal June-Oct",
        "kid_friendly": True,
        "activity_type": "family_walk",
        "difficulty": 1,
        "distance_km": 2.5,
        "elevation_gain_m": 40,
        "notes": "1.5-mile out-and-back on old mining road. Interpretive signs on 1870s mining. Gentle grade suitable for young children. Views of Owens Valley. Can combine with pack station visit for kids.",
        "sources": [("https://www.fs.usda.gov/recarea/inyo/recarea/?recid=20343", "official")]
    },
    {
        "name": "Sabrina Lake Shore Walk",
        "place_type": "trailhead",
        "lat": 37.2111,
        "lng": -118.6722,
        "address": "Lake Sabrina, North Lake Rd, Bishop, CA 93514",
        "parking_notes": "USFS fee lot $10; closes mid-Nov to late May; boat ramp nearby",
        "kid_friendly": True,
        "activity_type": "family_walk",
        "difficulty": 1,
        "distance_km": 2.0,
        "elevation_gain_m": 20,
        "notes": "1.2-mile lakeside stroll at 9,128 ft. Dam views, wildflower meadows July-Aug. High altitude—watch for altitude sickness in kids. Fishing pier. Boat rentals available.",
        "sources": [("https://www.fs.usda.gov/recarea/inyo/recarea/?recid=20323", "official")]
    },
    {
        "name": "Ancient Bristlecone Pine Discovery Trail",
        "place_type": "trailhead",
        "lat": 37.4167,
        "lng": -118.1833,
        "address": "Schulman Grove Visitor Center, White Mountain Rd, Bishop, CA 93514",
        "parking_notes": "USFS visitor center lot $5; 23 miles of gravel road; visitor center seasonal",
        "kid_friendly": True,
        "activity_type": "family_walk",
        "difficulty": 2,
        "distance_km": 1.6,
        "elevation_gain_m": 90,
        "notes": "1-mile interpretive loop at 10,000 ft among 4,000+ year old bristlecone pines (world's oldest trees). ADA accessible boardwalk option. Amazing high desert alpine environment. Start slow at altitude.",
        "sources": [
            ("https://www.fs.usda.gov/recarea/inyo/recarea/?recid=20343", "official"),
            ("https://www.nps.gov/deva/planyourvisit/whitemountains.htm", "official")
        ]
    },
    
    # RUNS
    {
        "name": "Bishop High Country 10K Loop",
        "place_type": "trailhead",
        "lat": 37.2361,
        "lng": -118.6111,
        "address": "South Lake Trailhead, Bishop Creek Canyon, Bishop, CA 93514",
        "parking_notes": "USFS fee lot $5; wilderness permit not needed for day use; bear canisters required for overnight",
        "kid_friendly": False,
        "activity_type": "run",
        "difficulty": 3,
        "distance_km": 10.0,
        "elevation_gain_m": 240,
        "notes": "6.2-mile loop combining Bishop Pass Trail and lake roads. 7,800-9,200 ft elevation. Trail and dirt road mix. Aspen groves, Sierra peaks. Best June-October. Bear country—be aware.",
        "run_type": "route",
        "sources": [("https://www.fs.usda.gov/recarea/inyo/recarea/?recid=20340", "official")]
    },
    {
        "name": "Buttermilk Country Trail Run",
        "place_type": "trailhead",
        "lat": 37.3367,
        "lng": -118.6456,
        "address": "Buttermilk Rd, Bishop, CA 93514",
        "parking_notes": "BLM free lot at Buttermilk; fills with climbers; no facilities",
        "kid_friendly": False,
        "activity_type": "run",
        "difficulty": 3,
        "distance_km": 8.0,
        "elevation_gain_m": 180,
        "notes": "5-mile out-and-back on dirt roads and trails through famous bouldering area. 5,200 ft elevation with views of Owens Valley. Connects to old mining roads. Morning best—afternoon heat.",
        "run_type": "route",
        "sources": [("https://www.blm.gov/visit/bishop-area", "official")]
    },
    {
        "name": "Bishop High Sierra Ultra",
        "place_type": "starting_point",
        "lat": 37.3614,
        "lng": -118.3950,
        "address": "Bishop City Park, Bishop, CA 93514",
        "parking_notes": "City lot; race day shuttles to remote start points",
        "kid_friendly": False,
        "activity_type": "run",
        "difficulty": 4,
        "distance_km": 50.0,
        "elevation_gain_m": 1800,
        "notes": "Annual Bishop High Sierra 50K/100K ultra (September). Routes through pine forests and high desert. 4,000-8,000 ft elevation. Race events; similar training routes available on local trails year-round.",
        "run_type": "event",
        "sources": [("https://bishopultra.com/", "official")]
    },
    
    # HIKES
    {
        "name": "Bishop Pass Trail",
        "place_type": "trailhead",
        "lat": 37.2111,
        "lng": -118.6722,
        "address": "South Lake Trailhead, North Lake Rd, Bishop, CA 93514",
        "parking_notes": "USFS fee lot $10; wilderness permit REQUIRED for overnight; bear canisters mandatory",
        "kid_friendly": False,
        "activity_type": "hike",
        "difficulty": 4,
        "distance_km": 17.7,
        "elevation_gain_m": 600,
        "notes": "11-mile round trip to Bishop Pass (11,972 ft). Stunning alpine lakes (Long, Saddlerock, Ruwau). JMT/PCT access. High Sierra peaks. Often snow until July. Thunderstorm risk afternoons.",
        "sources": [("https://www.fs.usda.gov/recarea/inyo/recarea/?recid=20340", "official")]
    },
    {
        "name": "Pine Creek Pass Trail",
        "place_type": "trailhead",
        "lat": 37.4611,
        "lng": -118.6683,
        "address": "Pine Creek Pass Trailhead, Pine Creek Rd, Bishop, CA 93514",
        "parking_notes": "USFS lot at pack station; free; high clearance recommended but not required",
        "kid_friendly": False,
        "activity_type": "hike",
        "difficulty": 4,
        "distance_km": 12.8,
        "elevation_gain_m": 750,
        "notes": "8-mile round trip through spectacular canyon to alpine basin at 11,200 ft. Waterfalls in spring. Abandoned tungsten mine ruins. Pass connects to wilderness beyond. Best July-September.",
        "sources": [("https://www.fs.usda.gov/recarea/inyo/recarea/?recid=20343", "official")]
    },
    {
        "name": "Hurd Peak via South Lake",
        "place_type": "trailhead",
        "lat": 37.2361,
        "lng": -118.6111,
        "address": "South Lake Trailhead, Bishop Creek Canyon, Bishop, CA 93514",
        "parking_notes": "USFS fee lot $5; day use; closes for snow",
        "kid_friendly": False,
        "activity_type": "hike",
        "difficulty": 4,
        "distance_km": 9.6,
        "elevation_gain_m": 550,
        "notes": "6-mile round trip off-trail scramble to 12,237 ft summit. Cross-country navigation skills required. Views of entire Bishop Creek basin. Peak bagging destination. Bring map and compass.",
        "sources": [("https://www.fs.usda.gov/recarea/inyo/recarea/?recid=20340", "official")]
    },
    {
        "name": "Meysan Lake Trail",
        "place_type": "trailhead",
        "lat": 36.7867,
        "lng": -118.2111,
        "address": "Meysan Lake Trailhead, Lone Pine Canyon, Lone Pine, CA 93545",
        "parking_notes": "USFS Whitney Portal lot; $10; wilderness permit required for Mt Whitney; fills early",
        "kid_friendly": False,
        "activity_type": "hike",
        "difficulty": 4,
        "distance_km": 12.0,
        "elevation_gain_m": 650,
        "notes": "7.5-mile round trip to Meysan Lake below Mt Whitney. Eastern Sierra dramatic peaks. Less crowded than main Whitney trail. 8,000-11,000 ft elevation. Stunning views of Alabama Hills.",
        "sources": [("https://www.fs.usda.gov/recarea/inyo/recarea/?recid=21617", "official")]
    },
    
    # BOULDERING
    {
        "name": "Buttermilk Boulders Main Area",
        "place_type": "starting_point",
        "lat": 37.3367,
        "lng": -118.6456,
        "address": "Buttermilk Rd, Bishop, CA 93514",
        "parking_notes": "BLM dirt lot; free; fills by 9am weekends; no facilities",
        "kid_friendly": False,
        "activity_type": "bouldering",
        "difficulty": None,
        "distance_km": None,
        "elevation_gain_m": None,
        "notes": "World-famous granite bouldering at 5,500 ft. 20+ distinct areas, 1000+ problems. Classics: 'Birthday Direct' (V3), 'Harvey' (V4). Featured in climbing films. Best Oct-May (summer hot). Bring 3+ pads.",
        "sources": [
            ("https://www.mountainproject.com/area/105731984/buttermilks", "web_search"),
            ("https://www.bishopvisitor.com/bouldering", "official")
        ]
    },
    {
        "name": "Happy Boulders",
        "place_type": "starting_point",
        "lat": 37.3467,
        "lng": -118.6611,
        "address": "Happy Boulders, Chalk Bluff Rd, Bishop, CA 93514",
        "parking_notes": "BLM lot; $2 donation suggested; 4WD recommended for rough access road",
        "kid_friendly": False,
        "activity_type": "bouldering",
        "difficulty": None,
        "distance_km": None,
        "elevation_gain_m": None,
        "notes": "Volcanic tuff bouldering (different rock type than Buttermilks). Higher density of problems, more shade. Grades V0-V10+. Often less crowded than Buttermilks. Good for mid-day sessions. Bring pads.",
        "sources": [("https://www.mountainproject.com/area/105731970/happy-boulders", "web_search")]
    },
    {
        "name": "Sad Boulders",
        "place_type": "starting_point",
        "lat": 37.3517,
        "lng": -118.6589,
        "address": "Sad Boulders, Buttermilk Country, Bishop, CA 93514",
        "parking_notes": "Hike in from Buttermilk parking; 0.5 mile approach; same lot as Buttermilks",
        "kid_friendly": False,
        "activity_type": "bouldering",
        "difficulty": None,
        "distance_km": None,
        "elevation_gain_m": None,
        "notes": "Adjacent to Happy Boulders. Similar volcanic tuff. Technical, crimpy problems. V2-V10 range. Good for working technique. Less crowded than main Buttermilk areas. Approach through sagebrush.",
        "sources": [("https://www.mountainproject.com/area/105732000/sad-boulders", "web_search")]
    },
]

SEQUOIA_KINGS_CANYON_DATA = [
    # WALKS
    {
        "name": "General Sherman Tree Walk",
        "place_type": "trailhead",
        "lat": 36.5800,
        "lng": -118.7519,
        "address": "General Sherman Tree Trail, Generals Hwy, Sequoia National Park, CA 93262",
        "parking_notes": "NPS paved lot; fills by 9am; shuttle available from Lodgepole; $35 park entry fee",
        "kid_friendly": True,
        "activity_type": "walk",
        "difficulty": 1,
        "distance_km": 1.0,
        "elevation_gain_m": 30,
        "notes": "0.6-mile paved loop to world's largest tree by volume (52,500 cu ft). Giant Forest wheelchair accessible. Fallen monarch tunnel. Information plaques. Most visited site in park.",
        "sources": [("https://www.nps.gov/seki/planyourvisit/g Sherman.htm", "official")]
    },
    {
        "name": "Grant Grove Loop",
        "place_type": "trailhead",
        "lat": 36.7486,
        "lng": -118.9664,
        "address": "Grant Grove Village, Generals Hwy, Kings Canyon National Park, CA 93633",
        "parking_notes": "NPS visitor center lot; free with park entrance; large paved area",
        "kid_friendly": True,
        "activity_type": "walk",
        "difficulty": 1,
        "distance_km": 1.6,
        "elevation_gain_m": 20,
        "notes": "1-mile paved interpretive loop through General Grant Grove. Second largest tree (General Grant). Open year-round—sometimes snow in winter. Holiday tree lighting ceremony each December.",
        "sources": [("https://www.nps.gov/seki/planyourvisit/grantgrove.htm", "official")]
    },
    {
        "name": "Cedar Grove River Walk",
        "place_type": "trailhead",
        "lat": 36.7947,
        "lng": -118.6658,
        "address": "Cedar Grove Visitor Center, Kings Canyon National Park, CA 93633",
        "parking_notes": "NPS visitor center lot; free; seasonal—closes with first heavy snow",
        "kid_friendly": True,
        "activity_type": "walk",
        "difficulty": 1,
        "distance_km": 2.4,
        "elevation_gain_m": 25,
        "notes": "1.5-mile riverside stroll along South Fork Kings River. Canyon floor at 4,600 ft. Sandy beaches for wading. Views of Grand Sentinel and North Dome. Best April-November.",
        "sources": [("https://www.nps.gov/seki/planyourvisit/cedargrove.htm", "official")]
    },
    
    # FAMILY WALKS
    {
        "name": "Big Trees Trail",
        "place_type": "trailhead",
        "lat": 36.5800,
        "lng": -118.7519,
        "address": "Giant Forest Museum, Generals Hwy, Sequoia National Park, CA 93262",
        "parking_notes": "Giant Forest Museum lot; shuttle access; free with park entrance",
        "kid_friendly": True,
        "activity_type": "family_walk",
        "difficulty": 1,
        "distance_km": 2.1,
        "elevation_gain_m": 15,
        "notes": "1.3-mile paved loop on meadow edge with views of massive sequoias. ADA accessible. Audio tour available. Ranger programs at museum. Sunset views of sequoias against meadow.",
        "sources": [("https://www.nps.gov/seki/planyourvisit/giantforest.htm", "official")]
    },
    {
        "name": "Auto Log Walk",
        "place_type": "trailhead",
        "lat": 36.5656,
        "lng": -118.7497,
        "address": "Auto Log, Generals Hwy, Sequoia National Park, CA 93262",
        "parking_notes": "Moro Rock parking area; shuttle stop; free with park entrance",
        "kid_friendly": True,
        "activity_type": "family_walk",
        "difficulty": 1,
        "distance_km": 0.5,
        "elevation_gain_m": 5,
        "notes": "Short walk to fallen sequoia once used as auto tunnel (now too decayed to drive on). Interpretive signs. Historic 1920s tourist attraction. Combine with Moro Rock climb.",
        "sources": [("https://www.nps.gov/seki/planyourvisit/mororock.htm", "official")]
    },
    {
        "name": "Zumwalt Meadow Loop",
        "place_type": "trailhead",
        "lat": 36.7944,
        "lng": -118.6658,
        "address": "Zumwalt Meadow Trailhead, Cedar Grove, Kings Canyon National Park, CA 93633",
        "parking_notes": "Cedar Grove area lot; free; seasonal road closure winter",
        "kid_friendly": True,
        "activity_type": "family_walk",
        "difficulty": 1,
        "distance_km": 2.4,
        "elevation_gain_m": 40,
        "notes": "1.5-mile boardwalk and trail through meadow with Kings River. Scenic heart of canyon. Suspension bridge crossing. Wildflowers June-July. Best views of granite canyon walls.",
        "sources": [("https://www.nps.gov/seki/planyourvisit/zumwalt.htm", "official")]
    },
    {
        "name": "Circle Meadow Loop",
        "place_type": "trailhead",
        "lat": 36.5750,
        "lng": -118.7508,
        "address": "Giant Forest area, Crescent Meadow Rd, Sequoia National Park, CA 93262",
        "parking_notes": "Crescent Meadow lot; shuttle access; seasonal road closure winter",
        "kid_friendly": True,
        "activity_type": "family_walk",
        "difficulty": 2,
        "distance_km": 2.4,
        "elevation_gain_m": 80,
        "notes": "1.5-mile loop through sequoia forest to Circle Meadow. Views of Moro Rock from forest. Log bridges, wildflowers. Quiet alternative to Sherman Tree crowds. Giant sequoias throughout.",
        "sources": [("https://www.nps.gov/seki/planyourvisit/crescentmeadow.htm", "official")]
    },
    
    # RUNS
    {
        "name": "Giant Forest Loop Run",
        "place_type": "trailhead",
        "lat": 36.5800,
        "lng": -118.7519,
        "address": "Giant Forest Museum, Generals Hwy, Sequoia National Park, CA 93262",
        "parking_notes": "Shuttle or park at museum lot; $35 park entrance; no fees on trail",
        "kid_friendly": False,
        "activity_type": "run",
        "difficulty": 3,
        "distance_km": 10.0,
        "elevation_gain_m": 280,
        "notes": "6.2-mile loop combining meadow trails and logging road connectors. 6,500 ft elevation. Sequoias, meadows, historic sites. Singletrack and old road mix. Best April-November.",
        "run_type": "route",
        "sources": [("https://www.nps.gov/seki/planyourvisit/giantforest.htm", "official")]
    },
    {
        "name": "Cedar Grove River Run",
        "place_type": "trailhead",
        "lat": 36.7947,
        "lng": -118.6658,
        "address": "Cedar Grove, Kings Canyon National Park, CA 93633",
        "parking_notes": "Visitor center lot; free; seasonal closure winter",
        "kid_friendly": False,
        "activity_type": "run",
        "difficulty": 2,
        "distance_km": 8.0,
        "elevation_gain_m": 120,
        "notes": "5-mile out-and-back along South Fork Kings River. Canyon floor at 4,600 ft. Flat to gentle grade. Sandy beaches for cool-off. Views of canyon walls. Shaded sections.",
        "run_type": "route",
        "sources": [("https://www.nps.gov/seki/planyourvisit/cedargrove.htm", "official")]
    },
    
    # HIKES
    {
        "name": "Moro Rock Trail",
        "place_type": "trailhead",
        "lat": 36.5458,
        "lng": -118.7661,
        "address": "Moro Rock Trailhead, Generals Hwy, Sequoia National Park, CA 93262",
        "parking_notes": "Moro Rock lot; shuttle access; fills early; $35 park entrance",
        "kid_friendly": True,
        "activity_type": "hike",
        "difficulty": 3,
        "distance_km": 0.8,
        "elevation_gain_m": 90,
        "notes": "0.5-mile climb to 6,725 ft dome summit. 400 steps carved in granite. Exposed stairs with handrails. Panoramic views of Great Western Divide, San Joaquin Valley. Fear of heights caution.",
        "sources": [("https://www.nps.gov/seki/planyourvisit/mororock.htm", "official")]
    },
    {
        "name": "Tokopah Falls Trail",
        "place_type": "trailhead",
        "lat": 36.6075,
        "lng": -118.7333,
        "address": "Lodgepole Campground, Generals Hwy, Sequoia National Park, CA 93262",
        "parking_notes": "Lodgepole visitor center lot; free with park entrance; market nearby",
        "kid_friendly": True,
        "activity_type": "hike",
        "difficulty": 3,
        "distance_km": 6.0,
        "elevation_gain_m": 190,
        "notes": "3.7-mile round trip to 1,200-ft falls on Kaweah River. Trail along river through lodgepole pine. Dramatic canyon walls. Falls may be dry by late summer. Early morning best for shade.",
        "sources": [("https://www.nps.gov/seki/planyourvisit/tokopah.htm", "official")]
    },
    {
        "name": "Mist Falls Trail",
        "place_type": "trailhead",
        "lat": 36.7944,
        "lng": -118.6658,
        "address": "Cedar Grove, Kings Canyon National Park, CA 93633",
        "parking_notes": "Canyon parking area; free; seasonal—road closes with snow",
        "kid_friendly": True,
        "activity_type": "hike",
        "difficulty": 3,
        "distance_km": 14.0,
        "elevation_gain_m": 180,
        "notes": "9-mile round trip along South Fork Kings River to Mist Falls. Gradual climb through canyon. Falls spray visible from trail. Continue to Paradise Valley for backpacking. Best April-October.",
        "sources": [("https://www.nps.gov/seki/planyourvisit/mistfalls.htm", "official")]
    },
    {
        "name": "Heather Lake Trail",
        "place_type": "trailhead",
        "lat": 36.5550,
        "lng": -118.7583,
        "address": "Wolverton Trailhead, Generals Hwy, Sequoia National Park, CA 93262",
        "parking_notes": "Wolverton lot; $35 park entrance; bear canisters required for overnight",
        "kid_friendly": False,
        "activity_type": "hike",
        "difficulty": 4,
        "distance_km": 18.0,
        "elevation_gain_m": 680,
        "notes": "11-mile round trip to Heather and Aster Lakes. Enters the Great Western Divide. High Sierra lakes, granite peaks. Elevation 7,200-10,400 ft. Often snow into July. Multi-day backpacking possible.",
        "sources": [("https://www.nps.gov/seki/planyourvisit/pear.htm", "official")]
    },
    {
        "name": "Rae Lakes Loop",
        "place_type": "trailhead",
        "lat": 36.7947,
        "lng": -118.6658,
        "address": "Roads End, Kings Canyon National Park, CA 93633",
        "parking_notes": "Roads End lot; free; wilderness permit required for overnight; limited spaces",
        "kid_friendly": False,
        "activity_type": "hike",
        "difficulty": 5,
        "distance_km": 66.0,
        "elevation_gain_m": 2400,
        "notes": "41-mile backpacking loop (multiple days) through some of Sierra's finest high country. Alpine lakes, passes over 11,000 ft, John Muir Trail section. Rae Lakes, Glen Pass. Permit required.",
        "sources": [
            ("https://www.nps.gov/seki/planyourvisit/raelakes.htm", "official"),
            ("https://www.nps.gov/seki/planyourvisit/wildernesspermits.htm", "official")
        ]
    },
]

if __name__ == "__main__":
    print("Bishop/Eastern Sierra data loaded:", len(BISHOP_EASTERN_SIERRA_DATA), "places")
    print("Sequoia/Kings Canyon data loaded:", len(SEQUOIA_KINGS_CANYON_DATA), "places")
