places = [
    # ─── WALK ───────────────────────────────────────────────────────────────────
    {
        "name": "Sand Harbor Beach Shoreline Walk",
        "place_type": "starting_point",
        "lat": 39.1987,
        "lng": -119.9314,
        "address": "2005 Highway 28, Incline Village, NV 89450",
        "parking_notes": "Pay parking lot on-site, $10 NV / $15 non-NV vehicles. Reservations required May 15–Sep 30 (8am–10:30am). No Hwy 28 roadside parking.",
        "kid_friendly": True,
        "source_url": "https://parks.nv.gov/parks/lake-tahoe-nevada-state-park",
        "source_type": "official",
        "activities": [
            {
                "activity_type": "walk",
                "difficulty": 1,
                "distance_km": 1.6,
                "elevation_gain_m": 5.0,
                "notes": "Sand Harbor to Memorial Point Trail (0.5 mi one-way) plus Sand Point Nature Trail (0.33 mi). Flat, paved/packed-gravel shoreline. Crystal-clear water views. ADA-accessible sections.",
                "run_type": None,
            },
            {
                "activity_type": "family_walk",
                "difficulty": 1,
                "distance_km": 0.5,
                "elevation_gain_m": 2.0,
                "notes": "Sand Point Nature Trail (0.33 mi) is fully handicap-accessible with interpretive signs and lake views. Perfect for all ages and abilities.",
                "run_type": None,
            },
        ],
    },
    {
        "name": "Tahoe East Shore Trail (Sand Harbor Segment)",
        "place_type": "trail",
        "lat": 39.2432,
        "lng": -119.9540,
        "address": "Tunnel Creek Staging Area, 1102 Tahoe Blvd, Incline Village, NV 89451",
        "parking_notes": "Park at Tunnel Creek Staging Area (1102 Tahoe Blvd). East Shore Express shuttle operates June–Aug. Day parking also at Sand Harbor lot.",
        "kid_friendly": True,
        "source_url": "https://parks.nv.gov/parks/lake-tahoe-nevada-state-park",
        "source_type": "official",
        "activities": [
            {
                "activity_type": "walk",
                "difficulty": 1,
                "distance_km": 4.83,
                "elevation_gain_m": 30.0,
                "notes": "3-mile paved multi-use bikeway from Incline Village south to Sand Harbor along Nevada's east shore. Flat, scenic lakeside path. Called 'America's Most Beautiful Bikeway'.",
                "run_type": None,
            },
            {
                "activity_type": "run",
                "difficulty": 2,
                "distance_km": 9.66,
                "elevation_gain_m": 60.0,
                "notes": "Out-and-back run on 3-mile paved East Shore Trail from Incline Village to Sand Harbor. Gentle grade, stunning lake views, minimal traffic.",
                "run_type": "route",
            },
        ],
    },
    {
        "name": "Burton Creek State Park",
        "place_type": "trailhead",
        "lat": 39.1868,
        "lng": -120.1250,
        "address": "Burton Creek State Park, northeast side of Tahoe City, CA 96145",
        "parking_notes": "Limited roadside parking at trailhead entry. No water, restrooms, or services on site. Open sunrise to sunset. No motorized vehicles.",
        "kid_friendly": True,
        "source_url": "https://www.parks.ca.gov/?page_id=512",
        "source_type": "official",
        "activities": [
            {
                "activity_type": "walk",
                "difficulty": 2,
                "distance_km": 9.66,
                "elevation_gain_m": 120.0,
                "notes": "6 miles of unpaved fire roads through coniferous forest on south-facing slopes of the north shore Tahoe Basin. South-facing slopes, seasonal wildflowers in spring, fall cottonwood color.",
                "run_type": None,
            },
            {
                "activity_type": "family_walk",
                "difficulty": 1,
                "distance_km": 4.0,
                "elevation_gain_m": 60.0,
                "notes": "Gentle fire road loops on northeast side of Tahoe City. Wildlife and bird watching. No traffic. Dogs allowed on fire roads (seasonal ski trail restrictions apply in winter).",
                "run_type": None,
            },
            {
                "activity_type": "run",
                "difficulty": 2,
                "distance_km": 9.66,
                "elevation_gain_m": 150.0,
                "notes": "Undeveloped fire road network near Tahoe City. Popular for trail running on packed dirt/gravel surfaces. Cross-country ski trails double as running routes in summer.",
                "run_type": "route",
            },
        ],
    },
    {
        "name": "Ed Z'berg Sugar Pine Point State Park – Shoreline",
        "place_type": "starting_point",
        "lat": 39.0492,
        "lng": -120.1159,
        "address": "Highway 89, 10 miles south of Tahoe City, Tahoma, CA 96142",
        "parking_notes": "Lakeside Day Use Area parking lot. $10/vehicle day use fee. Year-round self-pay when kiosk unstaffed. Visitors must park and walk to beach. Max trailer 26 ft.",
        "kid_friendly": True,
        "source_url": "https://www.parks.ca.gov/?page_id=510",
        "source_type": "official",
        "activities": [
            {
                "activity_type": "walk",
                "difficulty": 1,
                "distance_km": 3.2,
                "elevation_gain_m": 15.0,
                "notes": "Nearly 2 miles of Lake Tahoe frontage along the west shore. Flat lakeside walk past Hellman-Ehrman Mansion (Pine Lodge), pier, and nature center. Over 20km of marked trails in park.",
                "run_type": None,
            },
            {
                "activity_type": "family_walk",
                "difficulty": 1,
                "distance_km": 2.4,
                "elevation_gain_m": 10.0,
                "notes": "Flat shoreline path with swimming beach, pier, and nature center with bird and wildlife exhibits. Hellman-Ehrman Mansion tour available. Excellent for children.",
                "run_type": None,
            },
        ],
    },
    {
        "name": "Truckee River Legacy Trail",
        "place_type": "trail",
        "lat": 39.3272,
        "lng": -120.1833,
        "address": "Riverview Sports Park, 10696 Donner Pass Rd, Truckee, CA 96161",
        "parking_notes": "Free parking at Riverview Sports Park near Donner Pass Rd trailhead. Additional access at Tahoe Donner area trailheads.",
        "kid_friendly": True,
        "source_url": "https://www.truckee.com/",
        "source_type": "official",
        "activities": [
            {
                "activity_type": "walk",
                "difficulty": 1,
                "distance_km": 6.4,
                "elevation_gain_m": 20.0,
                "notes": "Paved multi-use path following the Truckee River through the town of Truckee. Flat, accessible, family-friendly. Connects downtown to recreational areas along the river corridor.",
                "run_type": None,
            },
            {
                "activity_type": "run",
                "difficulty": 1,
                "distance_km": 12.87,
                "elevation_gain_m": 35.0,
                "notes": "Paved riverside trail through Truckee. Popular local running route. Mostly flat with gentle grades. Connects multiple trailheads along the Truckee River. Great year-round access.",
                "run_type": "route",
            },
        ],
    },
    {
        "name": "Kings Beach State Recreation Area",
        "place_type": "starting_point",
        "lat": 39.2367,
        "lng": -120.0250,
        "address": "Kings Beach SRA, near Bear Street, Kings Beach, CA 96143",
        "parking_notes": "Year-round pay lots $10/day or $3/hour, 6am–9pm. Credit card only. RVs use Hwy 28/Raccoon lot. No beach parking for trailers.",
        "kid_friendly": True,
        "source_url": "https://www.parks.ca.gov/?page_id=511",
        "source_type": "official",
        "activities": [
            {
                "activity_type": "family_walk",
                "difficulty": 1,
                "distance_km": 1.6,
                "elevation_gain_m": 2.0,
                "notes": "979 feet of sandy beach frontage on the north shore. Flat lakeside stroll along sandy beach. Playground, basketball half-court, 18 picnic tables under Jeffrey pines. Dogs on leash on sidewalks/picnic areas (not beach).",
                "run_type": None,
            },
        ],
    },
    {
        "name": "Tahoe State Recreation Area – Tahoe City Commons Beach",
        "place_type": "starting_point",
        "lat": 39.1762,
        "lng": -120.1350,
        "address": "Highway 28, 0.25 miles east of Tahoe City, Tahoe City, CA 96145",
        "parking_notes": "Small campground parking area. Limited day-use parking. Bike path connects campground to Tahoe City downtown.",
        "kid_friendly": True,
        "source_url": "https://www.parks.ca.gov/?page_id=504",
        "source_type": "official",
        "activities": [
            {
                "activity_type": "family_walk",
                "difficulty": 1,
                "distance_km": 2.0,
                "elevation_gain_m": 5.0,
                "notes": "Flat lakeside walking along Tahoe City's Commons Beach and adjacent bike path to downtown. Beach access, lake views, picnic areas. Bike path leads into downtown Tahoe City. Best combined with Truckee River Legacy Trail.",
                "run_type": None,
            },
        ],
    },

    # ─── RUNS ───────────────────────────────────────────────────────────────────
    {
        "name": "Tahoe Rim Trail – Tahoe City to Brockway Summit Trailhead (64 Acres)",
        "place_type": "trailhead",
        "lat": 39.1646,
        "lng": -120.1474,
        "address": "64 Acres TRT Trailhead, off Fairway Dr, Tahoe City, CA 96145",
        "parking_notes": "64 Acres trailhead parking lot. Plowed in winter months. Access via Fairway Dr near Tahoe City. No fee. Fiberboard Freeway gate closes seasonally.",
        "kid_friendly": False,
        "source_url": "https://tahoerimtrail.org/",
        "source_type": "official",
        "activities": [
            {
                "activity_type": "run",
                "difficulty": 4,
                "distance_km": 32.99,
                "elevation_gain_m": 1097.0,
                "notes": "Tahoe City (64 Acres) to Brockway Summit segment: 20.5 miles one-way. Rugged lava cliffs, cinder cones, Watson Lake (treat water), Truckee River Canyon views. One of the most scenic TRT segments. Suitable for experienced trail runners.",
                "run_type": "route",
            },
            {
                "activity_type": "hike",
                "difficulty": 3,
                "distance_km": 16.1,
                "elevation_gain_m": 610.0,
                "notes": "Day hike out-and-back on TRT from 64 Acres toward Watson Lake (~5 miles one-way, 610m gain). Lava formations, cinder cones, forest, lake views. Watson Lake a scenic turnaround point.",
                "run_type": None,
            },
        ],
    },
    {
        "name": "Tahoe Rim Trail – Brockway Summit Trailhead",
        "place_type": "trailhead",
        "lat": 39.2647,
        "lng": -120.0468,
        "address": "Brockway Summit, Hwy 267, Kings Beach, CA 96143",
        "parking_notes": "Small pullout parking area at Brockway Summit on Hwy 267. No fee. Limited spaces. Access both north and south TRT segments.",
        "kid_friendly": False,
        "source_url": "https://tahoerimtrail.org/",
        "source_type": "official",
        "activities": [
            {
                "activity_type": "run",
                "difficulty": 5,
                "distance_km": 32.52,
                "elevation_gain_m": 1524.0,
                "notes": "Brockway Summit to Mt. Rose Summit / Tahoe Meadows: 20.2 miles one-way. Highest point on TRT is Relay Peak at 10,338 ft. Tremendous panoramic views. Requires shuttle or point-to-point logistics.",
                "run_type": "route",
            },
        ],
    },
    {
        "name": "Donner Lake Rim Trail – Donner Memorial State Park Trailhead",
        "place_type": "trailhead",
        "lat": 39.3175,
        "lng": -120.2356,
        "address": "Donner Memorial State Park, 12593 Donner Pass Rd, Truckee, CA 96161",
        "parking_notes": "Donner Memorial State Park day-use parking. Fee charged ($10/vehicle). Access to Donner Lake Rim Trail from east end of Donner Lake.",
        "kid_friendly": False,
        "source_url": "https://www.parks.ca.gov/",
        "source_type": "official",
        "activities": [
            {
                "activity_type": "run",
                "difficulty": 4,
                "distance_km": 29.94,
                "elevation_gain_m": 1158.0,
                "notes": "Donner Lake Rim Trail full loop (~18.6 miles). Circumnavigates Donner Lake with views of the Sierra. Mix of singletrack and fire road. ~3,800 ft gain full loop. Popular trail run and race course.",
                "run_type": "route",
            },
            {
                "activity_type": "hike",
                "difficulty": 3,
                "distance_km": 9.66,
                "elevation_gain_m": 518.0,
                "notes": "Out-and-back day hike on Donner Lake Rim Trail (~6 miles). Climb above Donner Lake for panoramic views of the lake and surrounding Sierra peaks. Trails range from moderate to strenuous.",
                "run_type": None,
            },
        ],
    },
    {
        "name": "Tahoe Rim Trail – Barker Pass Trailhead",
        "place_type": "trailhead",
        "lat": 39.0621,
        "lng": -120.2358,
        "address": "Barker Pass Rd, off Hwy 89, Tahoe City, CA 96145",
        "parking_notes": "Barker Pass Road (Blackwood Canyon Rd) off Hwy 89. Road open spring–fall; closed in winter depending on snowpack. Free parking at pass.",
        "kid_friendly": False,
        "source_url": "https://tahoerimtrail.org/",
        "source_type": "official",
        "activities": [
            {
                "activity_type": "run",
                "difficulty": 3,
                "distance_km": 26.38,
                "elevation_gain_m": 823.0,
                "notes": "Barker Pass to Tahoe City (64 Acres): 16.4 miles one-way. Abundant wildlife, creeks, wildflowers, Page Meadow. Mix of forested ridgeline and open meadow running. Popular TRT segment for point-to-point runs with shuttle.",
                "run_type": "route",
            },
        ],
    },
    {
        "name": "Western States 100 Start – Palisades Tahoe / Olympic Valley",
        "place_type": "starting_point",
        "lat": 39.1969,
        "lng": -120.2358,
        "address": "Palisades Tahoe Base Village, 1960 Squaw Valley Rd, Olympic Valley, CA 96146",
        "parking_notes": "Large Palisades Tahoe parking lots at base village. Free general parking. Race start is at west end of Olympic Valley at 5am on race day (last full weekend of June).",
        "kid_friendly": False,
        "source_url": "https://www.wser.org/course/",
        "source_type": "official",
        "activities": [
            {
                "activity_type": "run",
                "difficulty": 5,
                "distance_km": 161.0,
                "elevation_gain_m": 5516.0,
                "notes": "Western States 100 Mile Endurance Run. Starts at 6,200 ft elevation, climbs 2,550 ft to Emigrant Pass (8,750 ft) in first 4.5 miles. Total ~18,090 ft gain / ~22,970 ft descent to Auburn, CA. One of the world's most prestigious ultramarathons. Annual event last full weekend of June.",
                "run_type": "event",
            },
        ],
    },

    # ─── HIKES ──────────────────────────────────────────────────────────────────
    {
        "name": "Five Lakes Trail – Granite Chief Wilderness Trailhead",
        "place_type": "trailhead",
        "lat": 39.1856,
        "lng": -120.2367,
        "address": "Five Lakes Trailhead, Alpine Meadows Rd, near Palisades Tahoe, Olympic Valley, CA 96146",
        "parking_notes": "Small dirt parking area at end of Alpine Meadows Rd. Limited spaces (arrives full by 8–9am on weekends). No fee. No facilities.",
        "kid_friendly": False,
        "source_url": "https://www.fs.usda.gov/tahoe/",
        "source_type": "official",
        "activities": [
            {
                "activity_type": "hike",
                "difficulty": 3,
                "distance_km": 8.05,
                "elevation_gain_m": 427.0,
                "notes": "5-mile round-trip into Granite Chief Wilderness. Gains ~1,400 ft to a cluster of 5 alpine lakes at ~7,400 ft. Well-maintained trail with switchbacks through pine forest and granite. Swim in summer. Popular but rewarding.",
                "run_type": None,
            },
        ],
    },
    {
        "name": "Eagle Rock Trail – Homewood Area",
        "place_type": "trailhead",
        "lat": 39.0844,
        "lng": -120.1628,
        "address": "Eagle Rock Trailhead, Hwy 89 near Homewood, Tahoe City, CA 96145",
        "parking_notes": "Small roadside pullout off Hwy 89 near Homewood. No fee. Very limited parking, arrive early.",
        "kid_friendly": True,
        "source_url": "https://www.fs.usda.gov/tahoe/",
        "source_type": "official",
        "activities": [
            {
                "activity_type": "hike",
                "difficulty": 2,
                "distance_km": 3.22,
                "elevation_gain_m": 122.0,
                "notes": "Short 2-mile round-trip hike to Eagle Rock summit. ~400 ft gain. Outstanding panoramic views of Lake Tahoe and north shore. One of the best view hikes for effort in the area. Good for older children.",
                "run_type": None,
            },
        ],
    },
    {
        "name": "Castle Peak Trailhead – Donner Summit",
        "place_type": "trailhead",
        "lat": 39.3568,
        "lng": -120.3502,
        "address": "Castle Peak Trailhead, off Donner Pass Rd / Castle Peak Rd, I-80 exit 176, Soda Springs, CA 95728",
        "parking_notes": "Free USFS parking lot at trailhead off I-80 exit 176 (Castle Valley / Soda Springs). Toilet available. No fee. Can fill on weekends.",
        "kid_friendly": False,
        "source_url": "https://www.fs.usda.gov/tahoe/",
        "source_type": "official",
        "activities": [
            {
                "activity_type": "hike",
                "difficulty": 3,
                "distance_km": 11.27,
                "elevation_gain_m": 564.0,
                "notes": "7-mile round-trip to Castle Peak summit (9,103 ft). ~1,850 ft total gain. Passes Castle Valley, sub-peak, and exposed rocky summit with 360-degree views of Donner Summit area and Sierra crest.",
                "run_type": None,
            },
        ],
    },
    {
        "name": "Donner Peak Trailhead – Donner Summit",
        "place_type": "trailhead",
        "lat": 39.3289,
        "lng": -120.3241,
        "address": "Donner Peak / Pacific Crest Trail Trailhead, Donner Pass Rd, Donner Pass, CA 96161",
        "parking_notes": "Small pullout parking at Donner Pass on old Hwy 40 / Donner Pass Rd. Free. Limited spaces. PCT northbound access from pass.",
        "kid_friendly": False,
        "source_url": "https://www.fs.usda.gov/tahoe/",
        "source_type": "official",
        "activities": [
            {
                "activity_type": "hike",
                "difficulty": 3,
                "distance_km": 6.44,
                "elevation_gain_m": 381.0,
                "notes": "4-mile round-trip to Donner Peak summit (8,019 ft) via PCT. ~1,250 ft gain. Excellent views of Donner Lake and Truckee basin. Rocky exposed terrain near summit. Short but steep final push.",
                "run_type": None,
            },
        ],
    },
    {
        "name": "Tahoe Rim Trail – Twin Peaks Day Hike (Ward Creek Area)",
        "place_type": "trailhead",
        "lat": 39.1308,
        "lng": -120.1599,
        "address": "Ward Creek Park Property, Tahoma, CA 96142 (Ward Creek Blvd access)",
        "parking_notes": "Limited parking at Ward Creek / Ward Creek Blvd trailhead. No fee. No water or restrooms. Open sunrise to sunset.",
        "kid_friendly": False,
        "source_url": "https://www.parks.ca.gov/?page_id=513",
        "source_type": "official",
        "activities": [
            {
                "activity_type": "hike",
                "difficulty": 4,
                "distance_km": 14.48,
                "elevation_gain_m": 914.0,
                "notes": "9-mile round-trip day hike toward Twin Peaks (8,878 ft) via TRT from Ward Creek area. Dense forest transitions to sub-alpine terrain. ~3,000 ft gain. Solitary, undeveloped trails through Ward Creek's upland forest and meadowland.",
                "run_type": None,
            },
        ],
    },

    # ─── BOULDERING ─────────────────────────────────────────────────────────────
    {
        "name": "Donner Summit Bouldering Area",
        "place_type": "parking",
        "lat": 39.3289,
        "lng": -120.3195,
        "address": "Donner Pass Rd (Old Hwy 40), Donner Pass, CA 96161 (near Soda Springs, exit I-80 at Soda Springs / Norden exit)",
        "parking_notes": "Park along old Donner Pass Rd / Hwy 40. Free roadside parking. Multiple pullouts along the road. Best access from Soda Springs / Norden I-80 exit. No facilities.",
        "kid_friendly": False,
        "source_url": "https://www.fs.usda.gov/tahoe/",
        "source_type": "official",
        "activities": [
            {
                "activity_type": "bouldering",
                "difficulty": 3,
                "distance_km": 0.5,
                "elevation_gain_m": 30.0,
                "notes": "Donner Summit is one of the premier bouldering destinations in the Sierra Nevada, featuring hundreds of problems on high-quality granite. Problems range from V0 to V13+. Short approach from road. The area encompasses multiple boulder fields including the School Rock and Iron Door areas. Best season May–October. Elevation ~7,000 ft.",
                "run_type": None,
            },
        ],
    },
    {
        "name": "Donner Summit – School Rock Bouldering",
        "place_type": "parking",
        "lat": 39.3301,
        "lng": -120.3210,
        "address": "Old Hwy 40 / Donner Pass Rd, Donner Summit, CA 96161",
        "parking_notes": "Park at roadside pullouts on old Donner Pass Rd. School Rock is the most accessible cluster, visible from road. Free parking. No fee. Short walk uphill from pavement.",
        "kid_friendly": False,
        "source_url": "https://www.fs.usda.gov/tahoe/",
        "source_type": "official",
        "activities": [
            {
                "activity_type": "bouldering",
                "difficulty": 2,
                "distance_km": 0.2,
                "elevation_gain_m": 15.0,
                "notes": "School Rock at Donner Summit features approachable beginner-to-intermediate granite bouldering problems. V0–V5 concentration. Clean Sierra granite with excellent friction. 5–10 minute approach from parking. Ideal for learning bouldering technique in alpine setting.",
                "run_type": None,
            },
        ],
    },
    {
        "name": "Tahoe City Granite Slabs – General Creek Area",
        "place_type": "parking",
        "lat": 39.0570,
        "lng": -120.1220,
        "address": "Ed Z'berg Sugar Pine Point State Park – General Creek Campground, Hwy 89, Tahoma, CA 96142",
        "parking_notes": "Park at Sugar Pine Point State Park General Creek Campground / day use area. $10/vehicle day use. Walk toward lake-adjacent granite outcroppings.",
        "kid_friendly": False,
        "source_url": "https://www.parks.ca.gov/?page_id=510",
        "source_type": "official",
        "activities": [
            {
                "activity_type": "bouldering",
                "difficulty": 2,
                "distance_km": 0.8,
                "elevation_gain_m": 20.0,
                "notes": "Granite outcroppings and slabs in the Sugar Pine Point / General Creek drainage area. Lower-angle granite features with juggy holds. Good for beginners and intermediates. Part of the broader west shore Tahoe granite band. Less developed than Donner Summit but scenic lakeside setting.",
                "run_type": None,
            },
        ],
    },
]